CREATE TABLE `users` (
 `ID` int(10) NOT NULL AUTO_INCREMENT,
 `USERNAME` varchar(25) NOT NULL,
 `PASSWORD` varchar(25) NOT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1