CREATE TABLE `codebasicschooltype` (
 `BASICSCHOOLTYPEID` int(2) NOT NULL AUTO_INCREMENT,
 `SCHOOLTYPENAME` varchar(50) NOT NULL,
 PRIMARY KEY (`BASICSCHOOLTYPEID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1